using Microsoft.AspNetCore.Mvc.Rendering;

namespace JobSeeker.Constants
{
    public static class SpecialtiesList
    {
        public static readonly List<string> Specialties = new()
        {
            // التقنية والبرمجة
            "تطوير الويب",
            "تطوير تطبيقات الجوال",
            "تطوير البرمجيات",
            "برمجة Backend",
            "برمجة Frontend",
            "Full Stack Development",
            "تطوير الألعاب",
            "برمجة الأنظمة المدمجة",
            "برمجة Blockchain",
            "تطوير APIs",
            ".NET Development",
            "Java Development",
            "Python Development",
            "PHP Development",
            "Node.js Development",
            "React Development",
            "Angular Development",
            "Vue.js Development",
            "Flutter Development",
            "Swift Development",
            "Kotlin Development",
            "Android Development",
            "iOS Development",
            "الأمن السيبراني",
            "اختبار الاختراق",
            "إدارة الشبكات",
            "إدارة قواعد البيانات",
            "SQL Server",
            "Oracle Database",
            "MySQL",
            "PostgreSQL",
            "MongoDB",
            "DevOps",
            "Site Reliability Engineering",
            "الحوسبة السحابية",
            "AWS",
            "Azure",
            "Google Cloud",
            "Docker",
            "Kubernetes",
            "CI/CD",
            "إدارة البنية التحتية",
            "IT Support",
            "خدمات تقنية المعلومات",
            "إدارة المشاريع التقنية",
            "Product Management",
            "Business Analysis",
            "Systems Analysis",
            "Data Analysis",
            "Data Science",
            "Data Engineering",
            "Machine Learning",
            "Deep Learning",
            "Artificial Intelligence",
            "Natural Language Processing",
            "Computer Vision",
            "Big Data",
            "Business Intelligence",
            "Power BI",
            "Tableau",
            "Data Visualization",
            "Quality Assurance QA",
            "Software Testing",
            "Test Automation",
            "Performance Testing",
            "Manual Testing",
            "Technical Writing",
            "Documentation Engineering",

            // التصميم والإبداع
            "تصميم واجهات المستخدم UI",
            "تجربة المستخدم UX",
            "UI/UX Design",
            "Product Design",
            "Interaction Design",
            "Motion Design",
            "Animation Design",
            "تصميم الجرافيك",
            "تصميم الشعارات",
            "Brand Identity Design",
            "Print Design",
            "Packaging Design",
            "Publication Design",
            "تصميم الإعلانات",
            "تصميم الموشن جرافيك",
            "تحرير الفيديو",
            "Video Production",
            "Color Grading",
            "Sound Design",
            "Voice Over",
            "التصوير الفوتوغرافي",
            "تصوير المنتجات",
            "تصوير الفيديو",
            "تصميم داخلي",
            "تصميم معماري",
            "Landscape Design",
            "Fashion Design",
            "Textile Design",
            "Industrial Design",
            "3D Modeling",
            "3D Animation",
            "VFX",
            "Game Design",
            "Character Design",
            "Illustration",
            "Digital Art",
            "Calligraphy",
            "Typography",
            "Art Direction",
            "Creative Direction",

            // التسويق والإعلام
            "التسويق الرقمي",
            "Digital Marketing",
            "Performance Marketing",
            "Growth Marketing",
            "Content Marketing",
            "Inbound Marketing",
            "Outbound Marketing",
            "Affiliate Marketing",
            "Email Marketing",
            "Mobile Marketing",
            "Marketing Automation",
            "Marketing Strategy",
            "Brand Management",
            "Public Relations",
            "Media Relations",
            "Corporate Communications",
            "Copywriting",
            "Content Writing",
            "SEO",
            "SEM",
            "PPC Advertising",
            "Google Ads",
            "Facebook Ads",
            "Instagram Ads",
            "LinkedIn Ads",
            "TikTok Ads",
            "Snapchat Ads",
            "Twitter Ads",
            "Social Media Management",
            "Community Management",
            "Influencer Marketing",
            "Account Management",
            "Campaign Management",
            "Market Research",
            "Competitive Analysis",
            "Customer Insights",
            "Media Planning",
            "Media Buying",
            "Event Marketing",
            "Guerrilla Marketing",
            "Telemarketing",
            "Journalism",
            "Broadcast Journalism",
            "Radio Presenting",
            "TV Presenting",
            "Scriptwriting",
            "Screenwriting",
            "Editing",
            "Proofreading",
            "Translation",
            "Localization",
            "Interpretation",

            // الأعمال والإدارة
            "إدارة الأعمال",
            "Business Management",
            "Operations Management",
            "General Management",
            "Executive Management",
            "Office Management",
            "Administration",
            "Secretarial Work",
            "Executive Assistance",
            "Virtual Assistance",
            "Project Management",
            "Program Management",
            "Portfolio Management",
            "Agile Management",
            "Scrum Master",
            "Product Owner",
            "Change Management",
            "Risk Management",
            "Crisis Management",
            "Strategic Planning",
            "Business Development",
            "Partnerships Development",
            "Franchise Management",
            "Supply Chain Management",
            "Logistics Management",
            "Procurement",
            "Purchasing",
            "Inventory Management",
            "Warehouse Management",
            "Import/Export",
            "Operations Research",
            "Process Improvement",
            "Six Sigma",
            "Lean Management",
            "Quality Management",
            "ISO Compliance",
            "Customer Service",
            "Customer Support",
            "Customer Success",
            "Client Relations",
            "Technical Support",
            "Help Desk",
            "Call Center Management",
            "Sales Management",
            "Sales Operations",
            "Inside Sales",
            "Outside Sales",
            "B2B Sales",
            "B2C Sales",
            "Retail Sales",
            "Wholesale Sales",
            "Key Account Management",
            "Business Account Management",
            "Retail Management",
            "Store Management",
            "Merchandising",
            "E-commerce Management",
            "Marketplace Management",
            "Dropshipping",

            // المال والمحاسبة
            "المحاسبة",
            "Financial Accounting",
            "Management Accounting",
            "Cost Accounting",
            "Tax Accounting",
            "Auditing",
            "Internal Audit",
            "External Audit",
            "Forensic Accounting",
            "المالية",
            "Financial Analysis",
            "Financial Planning",
            "Financial Reporting",
            "Financial Modeling",
            "Investment Analysis",
            "Portfolio Management",
            "Wealth Management",
            "Asset Management",
            "Risk Analysis",
            "Credit Analysis",
            "Treasury Management",
            "Cash Management",
            "Budgeting",
            "Forecasting",
            "Banking",
            "Corporate Banking",
            "Retail Banking",
            "Islamic Banking",
            "Insurance",
            "Underwriting",
            "Claims Management",
            "Brokerage",
            "Real Estate Finance",
            "Mortgage Advisory",
            "Zakat and Tax",
            "VAT Consulting",
            "Financial Consulting",
            "ERP Consulting",

            // الموارد البشرية
            "الموارد البشرية",
            "Human Resources",
            "HR Generalist",
            "HR Administration",
            "Recruitment",
            "Talent Acquisition",
            "Executive Search",
            "Headhunting",
            "Talent Management",
            "Employee Relations",
            "Compensation and Benefits",
            "Payroll Management",
            "Performance Management",
            "Training and Development",
            "Learning and Development",
            "Organizational Development",
            "HR Analytics",
            "HR Information Systems",

            // الهندسة
            "الهندسة المدنية",
            "Structural Engineering",
            "Geotechnical Engineering",
            "Transportation Engineering",
            "Water Resources Engineering",
            "Environmental Engineering",
            "الهندسة المعمارية",
            "Landscape Architecture",
            "Urban Planning",
            "City Planning",
            "الهندسة الكهربائية",
            "Power Engineering",
            "Electronics Engineering",
            "Control Systems Engineering",
            "Telecommunications Engineering",
            "الهندسة الميكانيكية",
            "Automotive Engineering",
            "Aerospace Engineering",
            "Marine Engineering",
            "HVAC Engineering",
            "Mechatronics Engineering",
            "Robotics Engineering",
            "الهندسة الصناعية",
            "Manufacturing Engineering",
            "Production Engineering",
            "Mining Engineering",
            "Petroleum Engineering",
            "Chemical Engineering",
            "Biomedical Engineering",
            "Agricultural Engineering",
            "Food Engineering",
            "Nuclear Engineering",
            "Materials Engineering",
            "Metallurgical Engineering",
            "Surveying Engineering",
            "Quantity Surveying",
            "Construction Management",
            "Project Engineering",
            "Engineering Consulting",

            // الطب والصحة
            "الطب البشري",
            "General Practice",
            "Internal Medicine",
            "Cardiology",
            "Neurology",
            "Dermatology",
            "Ophthalmology",
            "ENT",
            "Pediatrics",
            "Obstetrics and Gynecology",
            "Orthopedics",
            "Surgery",
            "Anesthesiology",
            "Radiology",
            "Pathology",
            "Psychiatry",
            "Emergency Medicine",
            "Family Medicine",
            "Physical Therapy",
            "Occupational Therapy",
            "Speech Therapy",
            "التمريض",
            "Nursing",
            "Midwifery",
            "الصيدلة",
            "Pharmacy",
            "Clinical Pharmacy",
            "Laboratory Sciences",
            "Medical Laboratory",
            "Radiology Technology",
            "Dental Medicine",
            "Dentistry",
            "Oral Surgery",
            "Orthodontics",
            "Public Health",
            "Epidemiology",
            "Health Administration",
            "Healthcare Management",
            "Medical Coding",
            "Medical Billing",
            "Health Informatics",
            "Nutrition",
            "Dietetics",
            "Sports Nutrition",
            "Psychology",
            "Counseling",
            "Mental Health",
            "Social Work",
            "Veterinary Medicine",
            "Optometry",
            "Audiology",

            // التعليم
            "التعليم",
            "Teaching",
            "Early Childhood Education",
            "Primary Education",
            "Secondary Education",
            "Higher Education",
            "Special Education",
            "Educational Administration",
            "School Administration",
            "Curriculum Development",
            "Instructional Design",
            "E-learning Development",
            "Educational Technology",
            "Academic Advising",
            "Student Affairs",
            "Training Coordination",
            "Corporate Training",
            "Language Teaching",
            "English Teaching",
            "Arabic Teaching",
            "Mathematics Teaching",
            "Science Teaching",
            "Computer Science Teaching",

            // القانون
            "القانون",
            "Law",
            "Legal Consulting",
            "Corporate Law",
            "Commercial Law",
            "Labor Law",
            "Intellectual Property Law",
            "Contract Law",
            "Criminal Law",
            "Civil Law",
            "Family Law",
            "Real Estate Law",
            "Compliance",
            "Regulatory Affairs",
            "Legal Translation",
            "Paralegal",
            "Legal Secretarial",

            // العلوم والبحث
            "البحث العلمي",
            "Research and Development",
            "Market Research",
            "Scientific Research",
            "Clinical Research",
            "Biotechnology",
            "Biochemistry",
            "Microbiology",
            "Genetics",
            "Molecular Biology",
            "Chemistry",
            "Physics",
            "Mathematics",
            "Statistics",
            "Applied Mathematics",
            "Geology",
            "Geophysics",
            "Meteorology",
            "Environmental Science",
            "Agricultural Science",
            "Food Science",
            "Marine Science",

            // الفنون والإعلام
            "الموسيقى",
            "Music Production",
            "Sound Engineering",
            "الممثلين",
            "Acting",
            "Directing",
            "Film Production",
            "Documentary Production",
            "Cinematography",
            "Lighting Design",
            "Set Design",
            "Costume Design",
            "Makeup Artistry",
            "Hair Styling",
            "Fashion Styling",
            "Event Planning",
            "Wedding Planning",
            "Exhibition Management",

            // الضيافة والسياحة
            "إدارة الفنادق",
            "Hotel Management",
            "Hospitality Management",
            "Front Office Management",
            "Housekeeping Management",
            "Food and Beverage Management",
            "Restaurant Management",
            "Catering Management",
            "Tourism Management",
            "Travel Consulting",
            "Tour Guiding",
            "Aviation",
            "Cabin Crew",
            "Ground Handling",

            // الصناعة والحرف
            "Manufacturing",
            "Production Supervision",
            "Factory Management",
            "Plant Management",
            "Maintenance",
            "Electrical Maintenance",
            "Mechanical Maintenance",
            "Civil Maintenance",
            "Instrumentation",
            "Automation",
            "Plumbing",
            "Carpentry",
            "Welding",
            "Metal Fabrication",
            "Painting",
            "Electrical Works",
            "Air Conditioning Technician",
            "Automotive Technician",
            "Heavy Equipment Operator",
            "Forklift Operator",
            "Crane Operator",

            // الأمن والسلامة
            "Security Management",
            "Security Guard",
            "Safety Management",
            "Occupational Health and Safety",
            "Fire Safety",
            "Loss Prevention",
            "Surveillance",
            "Risk Assessment",

            // غير ذلك
            "غير ذلك"
        };

        public static List<SelectListItem> AsSelectListItems(string? selectedValue = null)
        {
            return Specialties.Select(s => new SelectListItem
            {
                Text = s,
                Value = s,
                Selected = s == selectedValue
            }).ToList();
        }
    }
}
